function choice = menuDialog()
        
    d = dialog('Position',[300 300 250 150],'Name','Suspect Report Generator');
    
    txt = uicontrol('Parent', d,...
                    'Style','text',...
                    'Position',[20 80 210 40],...
                    'String','Welcome To Suspect Report Generator. Start by Selecting a Department');
    
    popup = uicontrol('Parent',d,...
           'Style','popup',...
           'Position',[65 55 115 25],...
           'String',{'Fake Dept 1', 'Fake Dept 2'},...
           'Callback',@popup_callback);
       
    btn = uicontrol('Parent',d,...
           'Position',[85 20 70 25],...
           'String','Continue',...
           'Callback','delete(gcf)');
       
    choice = 'Red';
       
    % Wait for d to close before running to completion
    uiwait(d);
   
       function popup_callback(popup,event)
          idx = popup.Value;
          popup_items = popup.String;
          choice = char(popup_items(idx,:));
       end
end